### ISSUE TITLE
Check ELK stash as a log management tool

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#1132]
Here is what GPT suggests:

```
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
```

then configure logstash:
```
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [container_name] == "yaptide_redis" {
    # Redis log parsing
  } else if [container_name] == "yaptide_postgresql" {
    # PostgreSQL log parsing
  } else if [container_name] == "yaptide_flask" {
    # Flask log parsing
  } else if [container_name] == "yaptide_nginx" {
    # Nginx log parsing
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
```

then setup logs drivers:

```
services:
  redis:
    image: redis:7-alpine
    container_name: yaptide_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5000"

  postgresql:
    image: postgres:16-alpine
    container_name: yaptide_postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-yaptide_db}
      POSTGRES_USER: ${POSTGRES_USER:-yaptide_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yaptide_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $${POSTGRES_HOST:-postgresql} -p $${POSTGRES_PORT:-5432} -U $${POSTGRES_USER:-yaptide_user}"]
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5000"

  yaptide_flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: yaptide_flask
    container_name: yaptide_flask
    environment:
      - CELERY_BROKER_URL=redis://yaptide_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://yaptide_redis:6379/0
      - CERT_AUTH_URL=${CERT_AUTH_URL:-}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL:-}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-}
      - BACKEND_EXTERNAL_URL=${BACKEND_EXTERNAL_URL:-}
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql+psycopg://${POSTGRES_USER:-yaptide_user}:${POSTGRES_PASSWORD:-yaptide_password}@postgresql:5432/${POSTGRES_DB:-yaptide_db}
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5000"

  yaptide_worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    image: yaptide_worker
    container_name: yaptide_worker
    volumes:
      - simulators:/simulators:rw
    deploy:
      resources:
        limits:
          cpus: ${MAX_CORES-1.0}
    env_file: .env
    environment:
      - CELERY_BROKER_URL=redis://yaptide_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://yaptide_redis:6379/0
      - BACKEND_INTERNAL_URL=http://yaptide_flask:6000
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT:-WARNING}
    healthcheck:
      test: ["CMD-SHELL", "celery --app yaptide.celery.worker inspect ping"]
    depends_on:
      redis:
        condition: service_healthy
      yaptide_flask:
        condition: service_healthy
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5000"

  nginx:
    image: yaptide_nginx
    container_name: yaptide_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:5000
      - 8443:8443
    depends_on:
      yaptide_flask:
        condition: service_healthy
      yaptide_worker:
        condition: service_healthy
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5000"

volumes:
  esdata:
  data:
  simulators:
```
