### ISSUE TITLE
Improve docker compose health-checks

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#906]
Currently the healtchecks run with 30s interval.

This is the time needed to bring up container which are already built:

```bash
@grzanka ➜ /workspaces/yaptide (906-improve-docker-compose-health-checks) $ time docker compose up --detach
WARN[0000] /workspaces/yaptide/docker-compose.yml: `version` is obsolete 
[+] Running 5/6
 ⠴ Network yaptide_default       Created                                                                                                                                                    95.5s 
 ✔ Container yaptide_postgresql  Healthy                                                                                                                                                    32.1s 
 ✔ Container yaptide_redis       Healthy                                                                                                                                                    31.6s 
 ✔ Container yaptide_flask       Healthy                                                                                                                                                    62.7s 
 ✔ Container yaptide_worker      Healthy                                                                                                                                                    94.5s 
 ✔ Container yaptide_nginx       Started                                                                                                                                                    94.7s 

real    1m35.625s
user    0m0.414s
sys     0m0.120s
```

This example may be helpful to have faster startup using `start_period` and `start_interval` :

```
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      -  ./data-homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      zigbee2mqtt:
        condition: service_healthy
      mqtt:
        condition: service_healthy


  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data-zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 600s
      timeout: 4s
      retries: 6
      start_period: 30s
      start_interval: 5s
    depends_on:
      mqtt:
        condition: service_healthy

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ./data-mosquitto:/mosquitto
    ports:
      - 11883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 600s
      timeout: 3s
      retries: 5
      start_period: 20s
      start_interval: 4s
```

From  https://docs.docker.com/reference/dockerfile/#healthcheck we read:

> start interval is the time between health checks during the start period. This option requires Docker Engine version 25.0 or later.
